services:
  mysqldb:
    image: mysql:8
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: taskdb
    ports:
      - "3307:3306"
    volumes:
      - mysqldb_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  springboot-app:
    build: .
    container_name: springboot3-jwt-auth
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/taskdb?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_APPLICATION_NAME: springboot3-jwt-auth
      SERVER_PORT: 8080
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: always

volumes:
  mysqldb_data:
